# Generated by Django 6.1 on 2026-08-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=200)),
                ('Created_AT', models.DateField(auto_now=True)),
                ('isPublish', models.BooleanField(default=True)),
            ],
        ),
    ]
