# Generated by Django 6.1.1 on 2026-09-26 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_category_alter_product_collections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='bg_color',
            field=models.CharField(blank=True, default='#FFB86A', max_length=7),
        ),
        migrations.AddField(
            model_name='hero',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='hero',
            name='font_btn_color',
            field=models.CharField(blank=True, default='#FF6900', max_length=7),
        ),
    ]
